### ISSUE TITLE
ITMS-91107: Invalid tracking information

### ISSUE THREAD

**Issue by ermakov95** [appmetrica/appmetrica-react-native-plugin#4]
При отправке приложения на проверку в AppStore приходит такой ответ от них по поводу Манифеста конфиденциальности:

Although submission for App Store review was successful, you may want to correct the following issues in your next submission for App Store review. Once you've corrected the issues, upload a new binary to App Store Connect.

ITMS-91107: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “AppMetricaCore.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. Keys and values in any privacy manifest must be valid. For more details, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk.

**Comment by fredikey** [comment]
+, возникает такая же проблема

**Comment by NesterovichAlexey** [comment]
Проблема была в нативной части https://github.com/appmetrica/appmetrica-sdk-ios/issues/20.
И уже была исправлена в [AppMetrica iOS SDK 5.8.0](https://github.com/appmetrica/appmetrica-sdk-ios/releases/tag/5.8.0).
В скором времени выйдет новая версия плагина с этими изменениями.

**Comment by fredikey** [comment]
Супер, спасибо!

**Comment by NesterovichAlexey** [comment]
Проблема исправлена в версии [3.2.0](https://github.com/appmetrica/appmetrica-react-native-plugin/releases/tag/v3.2.0).
