### ISSUE TITLE
CocoaPods could not find compatible versions for pod "AppMetricaAnalytics":

### ISSUE THREAD

**Issue by vergsparda** [appmetrica/appmetrica-react-native-plugin#6]
![CleanShot 2024-10-28 at 12 35 11@2x](https://github.com/user-attachments/assets/13f6021f-6828-4d4d-be47-8bad3770c40b)

**Comment by dyrkow** [comment]
@vergsparda встретился с такой же проблемой при переходе с 3.0.0 до 3.1.0 и 3.2.0, подскажите, как вы решили эту проблему?

пробывал флаг --repo-update

**Comment by dyrkow** [comment]
Понял как это исправить,  оставлю тут, чтобы больше не было вопросов. 

![image](https://github.com/user-attachments/assets/df7117b7-30b6-4137-9957-2a41fb9f5694)

```
pod update AppMetricaAnalytics
```

**Comment by vergsparda** [comment]
> Понял как это исправить, оставлю тут, чтобы больше не было вопросов.
> 
> ![image](https://private-user-images.githubusercontent.com/8726541/386712272-df7117b7-30b6-4137-9957-2a41fb9f5694.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NTE2MTksIm5iZiI6MTczMTc1MTMxOSwicGF0aCI6Ii84NzI2NTQxLzM4NjcxMjI3Mi1kZjcxMTdiNy0zMGI2LTQxMzctOTk1Ny0yYTQxZmI5ZjU2OTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTZUMTAwMTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI4MmM3M2UyYWRjMzM0NjcyNzMwODIxNWY2NWI1OGUxY2NlYjU3MzNlNWRhMmJhZDJjZmY0ZGYwYTA0YzdiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pXuvwpI5ui5gRqhrqNXB2p-Q_1RTv1f1DcMECexN02k)
> 
> ```
> pod update AppMetricaAnalytics
> ```

Спасибо, надо попробовать.
